Repository NextUp-comedy/front-nc, pull requests merged in 2022-09, with the labels that each got.

#86 Create dashboard settings
  src/App.js
  src/Layout/Component.layout.jsx
  src/Layout/Dashboard.layout.jsx
  src/Layout/index.js
  src/app.css
  src/components/Dashboard/AddNewUser/index.jsx
  src/components/Dashboard/ChangePassword/index.jsx
  src/components/Dashboard/Content/ContentList/index.jsx
  src/components/Dashboard/Content/MatchContent/index.jsx
  src/components/Dashboard/DashboardSettings/index.jsx
  src/components/Dashboard/DashboardSettings/style.css
  src/components/Dashboard/SideBar/index.jsx
  src/components/Dashboard/index.js
  src/components/index.js
  src/pages/UserPages/Admin/DashboardSettings.page.jsx
  src/pages/UserPages/Admin/index.js
  src/pages/UserPages/Common/DashboardSettings.page.jsx
  src/pages/UserPages/Common/index.js
  src/pages/UserPages/EndUser/Revenue.page.jsx
  src/pages/UserPages/EndUser/StaffList.page.jsx
  src/pages/UserPages/EndUser/VideoList.page.jsx
  src/pages/UserPages/index.jsx
  src/services/admin.service.js
  src/shared/constants/endpoints/index.js
  src/shared/objects/sidebarItems.js
  src/store/admin/thunk.js
  src/store/matchContent/thunk.js
  src/utils/validation/forms.js
Labels: awaiting-review

#89 General updates
  .eslintrc.json
  src/App.js
  src/app.css
  src/components/AntDesign/AutoComplete/AutoComplete.jsx
  src/components/AntDesign/Avatar/Avatar.jsx
  src/components/AntDesign/Card/Card.jsx
  src/components/AntDesign/Col/Col.jsx
  src/components/AntDesign/ImgCrop/ImgCrop.jsx
  src/components/AntDesign/Pagination/Pagination.jsx
  src/components/AntDesign/Row/Row.jsx
  src/components/AntDesign/Spin/Spin.jsx
  src/components/AntDesign/index.js
  src/components/Authentication/LoginForm/index.jsx
  src/components/Authentication/RegisterForm/index.jsx
  src/components/Dashboard/AddNewUser/index.jsx
  src/components/Dashboard/ChangePassword/index.jsx
  src/components/Dashboard/Content/ContentList/index.jsx
  src/components/Dashboard/Content/ContentList/style.css
  src/components/Dashboard/Content/MatchContent/index.jsx
  src/components/Dashboard/EditProfile/index.jsx
  src/components/Dashboard/EditProfile/style.css
  src/components/Dashboard/NewUsers/Modal/RejectionReason.jsx
  src/components/Dashboard/NewUsers/Modal/index.jsx
  src/components/Dashboard/SideBar/index.jsx
  src/components/Navbar/index.jsx
  src/components/Navbar/style.css
  src/layouts/Component.layout.jsx
  src/layouts/Dashboard.layout.jsx
  src/layouts/index.js
  src/pages/UserPages/Admin/DashboardSettings.page.jsx
  src/pages/UserPages/EndUser/Revenue.page.jsx
  src/pages/UserPages/EndUser/StaffList.page.jsx
  src/pages/UserPages/EndUser/VideoList.page.jsx
  src/services/admin.service.js
  src/shared/components/Form/index.jsx
  src/shared/components/Logo/index.jsx
  src/shared/components/Table/index.jsx
  src/shared/constants/index.js
  src/store/admin/reducers.js
  src/store/admin/thunk.js
  src/store/auth/reducers.js
  src/store/matchContent/reducers.js
  src/store/matchContent/slice.js
  src/store/user/reducers.js
  src/utils/validation/forms.js
Labels: awaiting-review

#91 Handle the errors
  src/components/Dashboard/Content/MatchContent/index.jsx
  src/components/Dashboard/DashboardSettings/index.jsx
  src/utils/validation/forms.js
Labels: enhancement

#92 Edit users account
  src/components/Dashboard/EditProfile/style.css
  src/components/Dashboard/EditUserData/index.jsx
  src/components/Dashboard/index.js
  src/components/Navbar/index.jsx
  src/components/index.js
  src/pages/UserPages/Admin/EditUserData.page.jsx
  src/pages/UserPages/Admin/index.js
  src/pages/UserPages/index.jsx
  src/pages/index.js
  src/services/admin.service.js
  src/shared/components/Table/index.jsx
  src/shared/constants/endpoints/index.js
  src/shared/objects/Routes.js
  src/store/admin/reducers.js
  src/store/admin/thunk.js
Labels: awaiting-review

#100 edit endpoints according to the api
  src/shared/constants/endpoints/index.js
Labels: approved
