Repository NextUp-comedy/front-nc, pull requests merged in 2022-06, with the labels that each got.

#2 Created File Structure
  .env.example
  .eslintrc.json
  .gitattributes
  .gitignore
  .vscode/settings.json
  CODEOWNERS
  README.md
  babel.config.js
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/index.css
  client/src/index.js
  jest.config.js
  package-lock.json
  package.json
  readme.md
  server/src/__test__/index.test.ts
  server/src/app.ts
  server/src/controllers/error/index.ts
  server/src/controllers/index.ts
  server/src/database/config/buildDB.ts
  server/src/database/config/config.sql
  server/src/database/config/connections.ts
  server/src/database/config/index.ts
  server/src/database/fakeData/build.ts
  server/src/database/fakeData/fakeData.ts
  server/src/database/models/Categories.ts
  server/src/database/models/Roles.ts
  server/src/database/models/Tags.ts
  server/src/database/models/Uploads.ts
  server/src/database/models/UploadsCategories.ts
  server/src/database/models/UploadsTags.ts
  server/src/database/models/Users.ts
  server/src/database/models/index.ts
  server/src/index.ts
  server/src/routes/index.ts
  server/src/utilities/index.ts
  tsconfig.json
Labels: Approved

#9 added signup logic
  server/src/controllers/auth/signup.ts
  server/src/database/config/index.ts
  server/src/database/fakeData/build.ts
  server/src/database/fakeData/fakeData.ts
  server/src/database/models/Categories.ts
  server/src/database/models/Roles.ts
  server/src/database/models/Tags.ts
  server/src/database/models/Uploads.ts
  server/src/database/models/UploadsCategories.ts
  server/src/database/models/UploadsTags.ts
  server/src/database/models/Users.ts
  server/src/database/models/index.ts
  server/src/routes/auth/index.ts
  server/src/routes/index.ts
Labels: awaiting-review, backend

#11 [Backend] Verify user email
  .eslintrc.json
  client/package-lock.json
  package-lock.json
  package.json
  server/src/controllers/auth/index.ts
  server/src/controllers/auth/verify-email.ts
  server/src/controllers/index.ts
  server/src/utilities/index.ts
  server/src/utilities/jwt/index.ts
  server/src/utilities/jwt/sign-token.ts
  server/src/utilities/jwt/verify-token.ts
  server/src/utilities/send-email.ts
  server/src/utilities/validation-error.ts
  server/src/utilities/validation/index.ts
  server/src/utilities/validation/signup-schema.ts
Labels: awaiting-review, backend

#12 6 frontend register user
  client/src/App.js
  client/src/Assets/Images/NextUpLogo.png
  client/src/Assets/Images/authImage.png
  client/src/Components/Layout/Home.jsx
  client/src/Components/Layout/index.jsx
  client/src/Components/Layout/style.css
  client/src/Components/RegisterPage/RegisterForm.jsx
  client/src/Components/RegisterPage/index.jsx
  client/src/Components/RegisterPage/logo.jsx
  client/src/Components/RegisterPage/style.css
  client/src/Components/index.js
  client/src/Layouts/Home.jsx
  client/src/Pages/RegisterPage.jsx
  client/src/Pages/index.js
  package-lock.json
Labels: approved, Frontend
