Repository NextUp-comedy/front-nc, pull requests merged in 2022-07, with the labels that each got.

#18 Update Dashboard
  client/package-lock.json
  client/public/index.html
  client/src/App.js
  client/src/Components/Dashboard/SideBar/SideBarItem.jsx
  client/src/Components/Dashboard/SideBar/index.jsx
  client/src/Components/Dashboard/SideBar/sidebar.json
  client/src/Components/Dashboard/SideBar/style.css
  client/src/Components/Dashboard/index.js
  client/src/Components/Dashboard/index.jsx
  client/src/Components/Dashboard/style.css
  client/src/Components/Navbar/index.jsx
  client/src/Layouts/DashboardLayout.jsx
  client/src/Pages/UserPages/RevenuePage.jsx
  client/src/Pages/UserPages/UserDashboard.jsx
  client/src/Pages/UserPages/index.js
  client/src/Pages/index.js
  client/src/app.css
  package-lock.json
Labels: in-progress

#23 Forget Password
  .eslintrc.json
  package-lock.json
  package.json
  src/App.js
  src/Components/Authentication/ForgetPasswordForm/index.jsx
  src/Components/Authentication/GoogleAuth/index.jsx
  src/Components/Authentication/LogInForm/index.jsx
  src/Components/Authentication/RegisterForm/index.jsx
  src/Components/Authentication/RegisterForm/logo.jsx
  src/Components/Authentication/RegisterForm/style.css
  src/Components/Dashboard/SideBar/SideBarItem.jsx
  src/Components/index.js
  src/Pages/ForgetPasswordPage.jsx
  src/app.css
Labels: awaiting-review, Frontend

#26 Register Edit
  package.json
  src/Components/Authentication/RegisterForm/index.jsx
Labels: awaiting-review, Frontend

#28 Update Sidebar
  src/App.js
  src/Components/Authentication/ForgetPasswordForm/index.jsx
  src/Components/Authentication/LogInForm/index.jsx
  src/Components/Authentication/RegisterForm/index.jsx
  src/Components/Dashboard/SideBar/sidebar.json
  src/Components/Dashboard/SideBar/style.css
  src/Components/Navbar/index.jsx
  src/Components/Navbar/style.css
  src/Layouts/DashboardLayout.jsx
  src/Pages/UserPages/ChangePassword.jsx
  src/Pages/UserPages/DashboardSettings.jsx
  src/Pages/UserPages/EditProfile.jsx
  src/Pages/UserPages/PaymentSettings.jsx
  src/Pages/UserPages/PayoutPage.jsx
  src/Pages/UserPages/StaffList.jsx
  src/Pages/UserPages/Statistics.jsx
  src/Pages/UserPages/VideoList.jsx
  src/Pages/UserPages/index.js
  src/Pages/index.js
  src/app.css
Labels: approved

#38 36 create protected routes
  package-lock.json
  package.json
  src/App.js
  src/Components/Authentication/LogInForm/index.jsx
  src/Components/Dashboard/SideBar/index.jsx
  src/Store/Slices/checkAuthSlice.js
  src/Store/Slices/index.js
  src/Store/index.js
  src/index.js
  src/middleware/ProtectedRoutes.jsx
Labels: in-progress, Frontend

#40 Remove cookies visibility from dom
  src/App.js
  src/Components/Dashboard/MangeUser/index.jsx
  src/Hooks/userAuth.jsx
Labels: awaiting-review

#46 Update dashboard routes
  src/App.js
  src/Components/Dashboard/SideBar/sidebarItems.js
  src/Components/Dashboard/index.js
  src/Objects/Routes.js
  src/Pages/UserPages/EditProfile.jsx
  src/Pages/UserPages/EditProfilePage.jsx
  src/Pages/UserPages/UserDashboard.jsx
  src/Pages/UserPages/index.js
  src/Pages/index.js
Labels: awaiting-review, Frontend

#55 Organize user pages
  src/Components/Dashboard/EditProfile/index.jsx
  src/Components/Dashboard/NewUsers/index.jsx
  src/Components/Dashboard/NewUsers/style.css
  src/Components/Dashboard/RejectedUsers/index.jsx
  src/Components/Dashboard/UsersList/index.jsx
  src/Components/Dashboard/index.js
  src/Components/index.js
  src/Middleware/ProtectedRoutes.jsx
  src/Objects/Routes.js
  src/Objects/Users.js
  src/Pages/Authentication/ForgetPasswordPage.jsx
  src/Pages/Authentication/LogInPage.jsx
  src/Pages/Authentication/RegisterPage.jsx
  src/Pages/Authentication/ResetPasswordPage.jsx
  src/Pages/Authentication/VerifyEmailPage.jsx
  src/Pages/Authentication/index.js
  src/Pages/HomePage.jsx
  src/Pages/UserPages/Admin/NewUsersPage.jsx
  src/Pages/UserPages/Admin/RejectedUsersPage.jsx
  src/Pages/UserPages/Admin/UserListPage.jsx
  src/Pages/UserPages/Admin/index.js
  src/Pages/UserPages/Common/ChangePassword.jsx
  src/Pages/UserPages/Common/DashboardSettings.jsx
  src/Pages/UserPages/Common/EditProfilePage.jsx
  src/Pages/UserPages/Common/index.js
  src/Pages/UserPages/EndUser/PaymentSettings.jsx
  src/Pages/UserPages/EndUser/PayoutPage.jsx
  src/Pages/UserPages/EndUser/RevenuePage.jsx
  src/Pages/UserPages/EndUser/StaffList.jsx
  src/Pages/UserPages/EndUser/Statistics.jsx
  src/Pages/UserPages/EndUser/VideoList.jsx
  src/Pages/UserPages/EndUser/index.js
  src/Pages/UserPages/NewUsers.jsx
  src/Pages/UserPages/index.js
  src/Pages/index.js
Labels: enhancement, awaiting-review, Frontend
