Repository NextUp-comedy/front-nc, pull requests merged in 2022-08, with the labels that each got.

#61 Create Payment settings page
  .env.example
  package-lock.json
  package.json
  src/Assets/Images/payment.png
  src/Components/AntDesign/Avatar/index.jsx
  src/Components/AntDesign/Icons/DeleteOutlined/index.jsx
  src/Components/AntDesign/Icons/LoadingOutlined/index.jsx
  src/Components/AntDesign/Icons/PlusOutlined/index.jsx
  src/Components/AntDesign/ImgCrop/index.jsx
  src/Components/AntDesign/Upload/index.jsx
  src/Components/AntDesign/index.js
  src/Components/Authentication/ForgetPasswordForm/index.jsx
  src/Components/Authentication/LogInForm/index.jsx
  src/Components/Authentication/RegisterForm/index.jsx
  src/Components/Authentication/RegisterForm/logo.jsx
  src/Components/Authentication/ResetPasswordForm/index.jsx
  src/Components/Authentication/VerifyEmail/index.jsx
  src/Components/Dashboard/EditProfile/index.jsx
  src/Components/Dashboard/EditProfile/style.css
  src/Components/Dashboard/EditProfile/uploadImage/DeleteButton.jsx
  src/Components/Dashboard/EditProfile/uploadImage/UploadButton.jsx
  src/Components/Dashboard/EditProfile/uploadImage/index.jsx
  src/Components/Dashboard/EditProfile/uploadImage/style.css
  src/Components/Dashboard/NewUsers/index.jsx
  src/Components/Dashboard/PaymentSettings/PayComponents/AddData/AddData.jsx
  src/Components/Dashboard/PaymentSettings/PayComponents/EditData/EditData.jsx
  src/Components/Dashboard/PaymentSettings/PayComponents/index.js
  src/Components/Dashboard/PaymentSettings/index.jsx
  src/Components/Dashboard/PaymentSettings/style.css
  src/Components/Dashboard/RejectedUsers/index.jsx
  src/Components/Dashboard/SideBar/index.jsx
  src/Components/Dashboard/UsersList/index.jsx
  src/Components/Dashboard/index.js
  src/Components/Navbar/index.jsx
  src/Components/index.js
  src/Constants/config/index.js
  src/Constants/endpoints/index.js
  src/Constants/index.js
  src/Hooks/useAuth.jsx
  src/Hooks/userAuth.jsx
  src/Layouts/DashboardLayout.jsx
  src/Layouts/index.js
  src/Middleware/index.js
  src/Objects/Routes.js
  src/Pages/Authentication/ForgetPasswordPage.jsx
  src/Pages/Authentication/LogInPage.jsx
  src/Pages/Authentication/RegisterPage.jsx
  src/Pages/Authentication/ResetPasswordPage.jsx
  src/Pages/Authentication/VerifyEmailPage.jsx
  src/Pages/UserPages/EndUser/PaymentSettings.jsx
  src/Pages/UserPages/EndUser/PaymentSettingsPage.jsx
  src/Pages/UserPages/EndUser/RevenuePage.jsx
  src/Pages/UserPages/EndUser/index.js
  src/Pages/UserPages/index.js
  src/Pages/index.js
  src/Services/admin/index.js
  src/Services/user/index.js
  src/Utils/imageValidation.js
Labels: awaiting-review, Frontend

#65 Send reason of rejection
  src/Components/AntDesign/Modal/Modal.jsx
  src/Components/AntDesign/Radio/Radio.jsx
  src/Components/AntDesign/index.js
  src/Components/Dashboard/NewUsers/Modal/index.jsx
  src/Components/Dashboard/NewUsers/index.jsx
  src/Components/Dashboard/SideBar/index.jsx
  src/Objects/Routes.js
  src/Objects/sidebarItems.js
Labels: awaiting-review, Frontend

#64 BugFix: upload image
  src/Components/Dashboard/EditProfile/index.jsx
  src/Components/Dashboard/EditProfile/uploadImage/index.jsx
Labels: bug, approved

#69 Add new users page - Admin dashboard
  .eslintrc.json
  jsconfig.json
  src/Components/Dashboard/AddNewUser/index.jsx
  src/Components/Dashboard/AddNewUser/style.css
  src/Components/Dashboard/index.js
  src/Components/index.js
  src/Hooks/useAddUser.jsx
  src/Objects/Routes.js
  src/Objects/sidebarItems.js
  src/Pages/UserPages/Admin/AddNewUserPage.jsx
  src/Pages/UserPages/Admin/index.js
  src/Pages/UserPages/Common/EditProfilePage.jsx
  src/Pages/UserPages/index.js
  src/Pages/index.js
  src/Services/user/index.js
Labels: awaiting-review, Frontend

#41 sign up with google
  src/Components/Authentication/GoogleAuth/index.jsx
  src/Components/Authentication/LogInForm/index.jsx
  src/Components/Authentication/RegisterForm/index.jsx
  src/Pages/UserPages/Common/EditProfilePage.jsx
Labels: awaiting-review

#73 Fix some bugs
  src/Components/Dashboard/AddNewUser/index.jsx
  src/Components/Dashboard/NewUsers/index.jsx
  src/Components/Dashboard/RejectedUsers/index.jsx
  src/Components/Dashboard/SideBar/index.jsx
  src/Components/Dashboard/UsersList/index.jsx
  src/Constants/index.js
  src/Objects/Users.js
Labels: approved

#78 Create change password page
  src/Components/Dashboard/ChangePassword/index.jsx
  src/Components/Dashboard/ChangePassword/style.css
  src/Components/Dashboard/index.js
  src/Components/index.js
  src/Objects/Routes.js
  src/Pages/UserPages/Common/ChangePassword.jsx
  src/Pages/UserPages/Common/ChangePasswordPage.jsx
  src/Pages/UserPages/Common/index.js
  src/Pages/UserPages/index.js
  src/Pages/index.js
Labels: in-progress, Frontend

#81 Revert 78 77 create change password page
  src/Components/Dashboard/ChangePassword/index.jsx
  src/Components/Dashboard/ChangePassword/style.css
  src/Components/Dashboard/index.js
  src/Components/index.js
  src/Objects/Routes.js
  src/Pages/UserPages/Common/ChangePassword.jsx
  src/Pages/UserPages/Common/ChangePasswordPage.jsx
  src/Pages/UserPages/Common/index.js
  src/Pages/UserPages/index.js
  src/Pages/index.js
Labels: approved

#84 To redirect logged users to the same page asked before route protection check.
  src/middleware/ProtectLogin.jsx
  src/middleware/ProtectedRoutes.jsx
Labels: awaiting-review
